# Generated by Django 4.2.1 on 2023-06-01 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('description', models.TextField()),
                ('image_url_1', models.CharField(max_length=200)),
                ('image_url_2', models.CharField(max_length=200)),
                ('image_url_3', models.CharField(max_length=200)),
            ],
        ),
    ]
