# Generated by Django 4.2.1 on 2023-06-05 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_orderitem_userorder_orderitem_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userorder',
            name='products',
        ),
        migrations.AddField(
            model_name='userorder',
            name='shipping_address',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.shippingaddress'),
            preserve_default=False,
        ),
    ]
