# Generated by Django 4.2.1 on 2023-06-05 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_userorder_products_userorder_shipping_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='order',
            new_name='user_order',
        ),
    ]
