# Generated by Django 4.2.1 on 2023-06-05 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_rename_order_orderitem_user_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='user_order',
            new_name='order',
        ),
        migrations.RemoveField(
            model_name='userorder',
            name='shipping_address',
        ),
        migrations.AddField(
            model_name='userorder',
            name='products',
            field=models.ManyToManyField(through='myapp.OrderItem', to='myapp.product'),
        ),
    ]
